cleaning
cleanTodo

	"atCompletionPosition in RubSmalltalkEditor does not have to be defined in Reubric package since the only senders is NECControler. It should probably be repackaged in NECompletion package."
	
	"guessTypeForName: aString

	^nil
	is not well packaged: MorphicTextAdapter does not have to have a NOCompletion category but an extension of NECompletion"
	

	"RubEditingMode >> isCodeCompletion allowed is duplicated from superclass"