question
questionAboutTheLogicForBuildingEntry

	"
	when we have 
	
		self | 	the following can be class selectors + superclass
			
		another | the following can be any message depending on the type of another. 
			Question1: is the TypeGuesser invoked?
			
	 	instance variables, class variables arguments can be used when the text is empty or as method arguments:
		
		| sel -> self 
	
		
		foo 
			| xx -> xxx when the class or superclass has the xxx variable.
				
	
	
	"