to verify
toVerifyTwoDifferentModels

	"it looks like NEController has a model but this model is not a NECModel but more a tool like AbstractTool or FinderUI. Then in addition (to be verified) there is NECModel."
	
	"We verified the model of a controller is a model in the sense of MVC model. It is the model of a tool!!!! 
	Now the context has its own model which is a NECModel (an object representing information about a completion request. Now it is unclear if this model is created for all the ecompletion request. )
	
	
	
	"