design improvements
whatAboutCompletionAdditionalsForPlayground

	"apparently completionAdditionals is providing more local entry 
	to the completion based on the workspace binding.
	Now there is no such method for Playground only for Workspace.
	
	We will probably have to investigate whether we should create a Playground controller. 
	
	Now in Pharo6.1 it is strange because we cannot find a way to add bindings to Playground. The binding icon always displays an empty list: to be checked in Pharo70
	
	
	"